### ISSUE TITLE
COLMAP sfm testing output

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#26]
Currently there is no way to evaluate the quality of the output of structure from motion without running the time consuming TensoRF code and comparing outputs. We need a faster way to test the sfm portion of the code so we can debug and analyze it's baseline performance. Specifically, we need a way to compare the intrinsic and extrinsic matrices generated for each scene with the ground truth data from the nerf-synthetic dataset. This will fall under camera calibration.

**Comment by xxanxnie** [comment]
to_cam.py helped with visualization
