### ISSUE TITLE
MongoDB license conflict

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#28]
MongoDB has a custom license https://www.mongodb.com/licensing/server-side-public-license. This must be evaluated for inclusion in our MIT-licensed project.

**Comment by panzertonBirdsong** [comment]
For a project based on the program under this license, authors must a) state the modification as well as dates; b)state it is released under this license; c) make the entire project under this license; d) display an appropriate legal notice on the interactive user interface(if exists).
