### ISSUE TITLE
Debugging output for COLMAP

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#36]
Currently, COLMAP failures are hard to debug since running the script fails to provide output on each step in COLMAP's running. 
To mitigate this the following should be implemented:
1.) Detailed printouts should happen on each step of the COLMAP worker's execution aswell as the ffmpeg.
2.) Avoid COLMAP's output dumping to the terminal: COLMAP's output should be piped to an output file and saved locally under each job id to the worker for debugging purposes (maybe a flag to enable this as well?). 
3.) Automatically run the to_cam.py and save the resulting figure (hopefully in a way that allows interactive rendering rather than a png) to the job id folder.
4.) Use the extrinsic matrices generated to print out general statistics about the camera locations (After NDC and all coordinate conversions). Use the formula below to get the camera point and run basic statistics like min max for each coordinate, average point across all cameras, maybe standard deviation across each axis x,y,z, and anything else that may be useful.
![f19e012ff28e9a5ad8364c2fed39818c04d0f6ca](https://user-images.githubusercontent.com/49171429/185013154-65024fc0-3990-4e41-8dd4-8fe0a1eba4f2.svg)
^ source https://en.wikipedia.org/wiki/Camera_resectioning

**Comment by AidanWestphal** [comment]
Finished
