### ISSUE TITLE
Sub-sampling video frames for longer videos

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#37]
Right now videos sent to the sfm worker are assumed to be 24 fps and are broken into frames accordingly. This can result in excessive amounts of images for relatively short videos. To remedy this the worker should have a max frame count that will contain the upper bound for the number of images COLMAP will process uniformly sampled from the input video. Along with this on the output side of the worker, a second filter should be applied to the output data to filter the frames down to ~100-200 high-quality frames to be sent to TensoRF.  

- For the input filter a uniform sampling can be used since nothing is known about the video yet

- For the output filter there are a few design decisions to keep in mind as we can leverage the COLMAP output to select optimal images to feed to TensoRF. These images would ideally be, uniformly distributed in 3D space, from a variety of angles of the subject, with significant visual overlap, without motion blur or other artifacts. This output filter can become an endeavor within itself so for an initial implementation simply randomly sample the output data from COLMAP to 100~200 images then work towards the 3D space sampling.

NOTE: Resolution may also have to be a factor in selecting image sets and downscaling may need to be performed at the input filter stage in order to manage the compute times of COLMAP and TensoRF

**Comment by alexandorr55** [comment]
The new max_frames parameter in split_video_into_frames (in video_to_images.py) should help with this problem.

**Comment by PotatoPalooza** [comment]
Resolved in #63 . This will be moved to the webserver in an upcoming update
