### ISSUE TITLE
Graceful handling of missing Microservices

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#43]
Right now the webserver and colmap worker crash if their dependent services are not up and running. This becomes an issue as their initializations in dockers vary in time so it is likely the webserver will boot before the db is up. The webserver and colmap worker should report the service that failed to connect and retry the connection before crashing.

**Comment by PotatoPalooza** [comment]
https://pika.readthedocs.io/en/stable/examples/blocking_consume_recover_multiple_hosts.html

**Comment by AzurDragRay** [comment]
In vidtonerf/web-server/services/queue_service.py, is where the issue is located. Specifically, in the class RabbitMQService, in def _init_(self)
