### ISSUE TITLE
Handling Blurry Videos in COLMAP

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#72]
Currently nothing happens when a video is deemed too blurry to perform structure from motion in the split_video_into_frames function. This flag should be captured and sent back to the web-server so the user can be notified their video was too blurry to generate a nerf. 

The current job should be acknowledged as complete as seen on line 129 in colmap's main and an update should be pushed to the web-server through the sfm-out que to indicate the failure. Once this is completed the Readme will need to be updated with the new communication standard and the web server should be updated to internalize this incoming signal.

**Comment by PotatoPalooza** [comment]
Step 1: Capture Blurry Video Flag
Step 2: Send Flag to web-server via the sfm-out que
Step 3: Acknowledge Completion of the current job to RabbitMQ
Step 4: Update Readme to reflect this new communication
Step 5: Update Web Server to internalize this new flag with a new endpoint to notify the user

**Comment by AidanWestphal** [comment]
Finished
