### ISSUE TITLE
COLMAP Camera model decision

### ISSUE THREAD

**Issue by PotatoPalooza** [NeRF-or-Nothing/vidtonerf#8]
It is necessary to evaluate how much the simple pinhole camera model affects the quality of rendered videos as it does not account for lens distortion. In the future, it may be a good idea to look into radial models that attempt to model this distortion as another matrix transformation. With the current COLMAP backend, this can be found here: https://colmap.github.io/cameras.html. This method may improve the quality of SFM but could add complexity and runtime.

**Comment by panzertonBirdsong** [comment]
First impression is that no obvious computation is added for the (Simple) Pinhole Camera model. It might even require the least computation among the four. (https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h).

**Comment by PotatoPalooza** [comment]
Simple Pinhole looks to be good for now, maybe we can run some tests in the future to measure the difference this makes
